# Generated by Django 2.2.6 on 2019-10-31 18:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Název')),
                ('type_photo', models.IntegerField(verbose_name='Číslo typu')),
            ],
            options={
                'verbose_name': 'Typ fotky',
                'verbose_name_plural': 'Typy fotek',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Název')),
                ('photo', models.ImageField(upload_to='stranka/')),
                ('home_page_photo', models.BooleanField(default=False, verbose_name='Zobratovat na homepage')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('photo_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.PhotoType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fotka',
                'verbose_name_plural': 'Fotky',
            },
        ),
    ]
