# Generated by Django 2.2.6 on 2019-11-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20191101_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototype',
            name='main_type_photo',
            field=models.BooleanField(default=False, verbose_name='Zobrazovat jako náhled na kategorii'),
        ),
    ]
