# Generated by Django 2.2.6 on 2019-11-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_phototype_main_type_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='type_galeri_photo',
            field=models.BooleanField(default=False, verbose_name='Zobraovat jako náhled na ketegorii'),
        ),
    ]
