# Generated by Django 2.2.6 on 2020-01-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_photo_type_galeri_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='slider_photo',
            field=models.BooleanField(default=False, verbose_name='Zobrazovat ve slideru'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='type_galeri_photo',
            field=models.BooleanField(default=False, verbose_name='Zobrazovat jako náhled na ketegorii'),
        ),
    ]
